---
# tasks file for k8s_worker
- name: Installing docker services
  package:
      name: docker
      state: present
- name: Starting Docker Services
  service:
      name: docker
      state: started
      enabled: yes
- name: Setting yum repo for kubernetes
  yum_repository:
          name: Kubernetes
          description: kubernetes repo
          file: kubernetes
          baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
          gpgcheck: 1
          enabled: 1
          gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          repo_gpgcheck: 1
  changed_when: false
- name: Installing kubernetes softwares
  package:
      name: "{{ item }}"
      state: present
  loop:
    - kubeadm
    - iproute-tc
    - kubectl
- name: Enabling kubelet service
  service:
      name: kubelet
      state: started
      enabled: yes
- name: Setting up driver required by kubernetes
  copy:
    dest: /etc/docker/daemon.json
    content: |
       {
         "exec-opts": ["native.cgroupdriver=systemd"]
       }
- name: Restarting Docker services
  service:
     name: docker
     state: restarted
  changed_when: false
- name: Setting up IP table
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
       net.bridge.bridge-nf-call-ip6tables = 1
       net.bridge.bridge-nf-call-iptables = 1
  changed_when: false
- name: Restarting systemctl
  shell: "sudo sysctl --system"
  changed_when: false
- name: Running Token Files
  shell: "{{ master_token }}"








  



